Add label to message.broadcast and metrics
netology-group/conference pull request #146
Opened 2020-09-07 16:04 UTC by feymartynov

2020-09-07 16:18 UTC, manifest approved these changes

2020-09-07 16:25 UTC, khodzha requested changes

2020-09-07 16:25 UTC, khodzha commented on src/app/context.rs
> +        self.dynamic_stats.as_ref().map(|stats| &**stats)
`as_deref()` тут не получится использовать?

2020-09-07 16:25 UTC, khodzha commented on src/app/metrics/dynamic_stats_collector.rs
> +                    Message::Flush => {
я бы слал прям в `Message::Flush` `Sender`а для `bounded(1)` канала

2020-09-07 16:25 UTC, khodzha commented on src/app/metrics/dynamic_stats_collector.rs
> +                    Message::Flush => {
типа так
https://github.com/netology-group/svc-agent-rs/blob/c404a55e3577dea7d863f2fee3535a50e54d9ca8/src/queue_counter.rs#L101-L102

2020-09-07 16:25 UTC, khodzha commented on src/app/metrics/dynamic_stats_collector.rs
> +            warn!("Failed to stop dynamic stats collector: {}", err);
`{:?}`

2020-09-07 16:25 UTC, khodzha commented on src/app/metrics/dynamic_stats_collector.rs
> +            warn!("Failed to register dynamic stats collector value: {}", err);
`{:?}`

2020-09-07 16:25 UTC, khodzha commented on src/app/metrics/dynamic_stats_collector.rs
> +                            warn!("Failed to send dynamic stats collector report: {}", err);
`{:?}`

2020-09-07 16:25 UTC, khodzha commented on src/app/metrics/dynamic_stats_collector.rs
> +            .map_err(|err| anyhow!(err.to_string()))
тут `err.to_string()` не проглотит всю информацию по ошибке?

2020-09-07 16:25 UTC, khodzha commented on src/app/metrics/dynamic_stats_collector.rs
> +    pub(crate) fn collect(&self, key: impl Into<String>, value: usize) {
тут нужны этот `impl` и `value`?

2020-09-08 08:57 UTC, feymartynov commented on src/app/metrics/dynamic_stats_collector.rs
> +    pub(crate) fn collect(&self, key: impl Into<String>, value: usize) {
В принципе можно и без них, т.к. это сейчас в одном месте используется, но это типа, чтобы не зашиваться на конкретный кейс и переиспользовать потом ещё где-то.

2020-09-08 09:08 UTC, khodzha approved these changes

2020-09-08 09:15 UTC, merged